### ISSUE TITLE
"load() could not be fired"

### ISSUE THREAD

**Issue by SamuelSHrk** [sh6un/BetterDiscord-Stereo-Files#1]
I'm trying to get your plugins to work but I get this error 
![error](https://user-images.githubusercontent.com/43790833/197426007-9da278f3-6090-41b4-91b9-1b461e60805b.PNG)

**Comment by sh6un** [comment]
Download the most updated version of ZeresPluginLibrary here : 
https://betterdiscord.app/plugin/ZeresPluginLibrary
This plugin library is made by zerebos, not me.

**Comment by SamuelSHrk** [comment]
> Download the most updated version of ZeresPluginLibrary here : 
> https://betterdiscord.app/plugin/ZeresPluginLibrary
> This plugin library is made by zerebos, not me.

That's what I figured, i thought it was a whole separate plugin library and you made special modifications for the stereo to work. Either way I did download the regular plugin library and a friend in a voice chat did say my mic was finally in stereo so thanks.
